# **Series**

**다차원 인덱싱**
- 다차원 인덱싱에서는 :(콜론)을 기준으로 행과 열을 분리하여 인덱싱한다.

In [8]:
import numpy as np

In [9]:
arr = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
arr[2, :] # 행의 인덱스가 2인 값 추출

array([ 8,  9, 10, 11])

In [10]:
arr[1:3, ] # 행의 인덱스가 1, 2인 값 추출

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
arr[:, 1] # 열의 인덱스가 1인 값 추출

array([1, 5, 9])

In [12]:
arr[:, 1:3] # 열의 인덱스가 1, 2인 값 추출

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [13]:
arr[2,3] # 행의 인덱스가 2, 열의 인덱스가 3인 값 추출

11

**Fancy Indexing**
- 정수나 Boolean 값을 가지는 다른 numpy 배열로 배열을 인덱싱할 수 있는 기능을 의미
- Boolean 값을 가진 배열을 사용하여 직관적으로 인덱싱 가능

팬시 인덱싱(fancy indexing)은 배열의 원소를 접근하거나 수정하는 방법 중 하나로, NumPy라는 파이썬 패키지에서 제공되는 기능입니다. 이 기능은 배열의 특정한 인덱스 집합을 사용하여 해당 위치에 있는 원소에 접근하거나 수정하는 데 사용됩니다.

일반적인 인덱싱 방법은 정수 인덱스를 사용하여 원소에 접근하는 것이지만, 팬시 인덱싱에서는 정수 배열 또는 부울 배열을 사용하여 원하는 위치의 원소에 접근할 수 있습니다. 이는 단순한 슬라이싱을 넘어서 더 다양한 방식으로 배열의 원소를 선택할 수 있게 해줍니다.

https://chuyinchule.tistory.com/5

In [14]:
import numpy as np

a = np.arange(15).reshape(5,3)
a


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [15]:
a[[0,2,4]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [16]:
a[:,1]

array([ 1,  4,  7, 10, 13])

In [17]:
a[:,[0,2]]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11],
       [12, 14]])

In [18]:
a[[0,2,4]][:,[0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14]])

In [19]:
arr = np.array([1,2,3,4,5])

In [20]:
indices = np.array([1,3,4])
indices

array([1, 3, 4])

In [21]:
arr[indices]

array([2, 4, 5])

In [22]:
import pandas as pd

In [23]:
np.random.seed(0)
s = pd.Series(np.random.randint(10000, 20000, size=(10)))
s

0    12732
1    19845
2    13264
3    14859
4    19225
5    17891
6    14373
7    15874
8    16744
9    13468
dtype: int32

In [24]:
s > 15000

0    False
1     True
2    False
3    False
4     True
5     True
6    False
7     True
8     True
9    False
dtype: bool

In [25]:
# 인덱스에서 데이터 필터링 가능

s[s>15000]

1    19845
4    19225
5    17891
7    15874
8    16744
dtype: int32

In [26]:
s[(s>=13000) & (s<=15000)]

2    13264
3    14859
6    14373
9    13468
dtype: int32

In [27]:
s = pd.Series(['마케팅', '경영', '개발', '기획', '인사'], index=['a', 'b', 'c', 'd', 'e'])
s

a    마케팅
b     경영
c     개발
d     기획
e     인사
dtype: object

In [28]:
#먼저, Series를 생성 후 index 속성 값에 새로운 index를 할당하여 인덱스를 지정할 수 있습니다.

s = pd.Series(['마케팅', '경영', '개발', '기획', '인사'])
s.index = list('abcde')
s

a    마케팅
b     경영
c     개발
d     기획
e     인사
dtype: object

Sclicing
- 숫자형 인덱스로 접근할 때에는 index-1까지 접근
- 문자열 인덱스로 접근할 때에는 끝 index 모두 포함

연습문제

In [29]:
import pandas as pd
import numpy as np

arr = pd.Series(np.arange(3.0,12.0,2.0), dtype='float32')
arr

0     3.0
1     5.0
2     7.0
3     9.0
4    11.0
dtype: float32

In [30]:
arr = pd.Series(["가","나","다","라","마"])
arr

0    가
1    나
2    다
3    라
4    마
dtype: object

In [31]:
sample = pd.Series(np.arange(10,60,10))
sample.index = list('가나다라마')
sample

가    10
나    20
다    30
라    40
마    50
dtype: int32

In [32]:
sample[[1,3]]

나    20
라    40
dtype: int32

In [33]:
np.random.seed(20)
sample2 = pd.Series(np.random.randint(100,200,size=(15,)))
sample2

0     199
1     190
2     115
3     195
4     128
5     190
6     109
7     120
8     175
9     122
10    171
11    134
12    196
13    140
14    185
dtype: int32

In [34]:
sample2[sample2<160]

2     115
4     128
6     109
7     120
9     122
11    134
13    140
dtype: int32

In [35]:
sample.tmp = sample2[sample2<=170]
result = sample.tmp[sample.tmp>=130]
result

11    134
13    140
dtype: int32

In [36]:
## 더 좋은 방법
sample2[(sample2 >= 130) & (sample2 <= 170)]

11    134
13    140
dtype: int32

In [37]:
s = pd.Series(["apple", np.nan, "banana", "kiwi", "gubong"])
s.index = list('가나다라마')
s

가     apple
나       NaN
다    banana
라      kiwi
마    gubong
dtype: object

In [38]:
sample = pd.Series(['IT서비스', np.nan, '반도체', np.nan, '바이오', '자율주행'])
sample

sample[sample.isnull()]

1    NaN
3    NaN
dtype: object

In [39]:
sample[sample.notnull()]

0    IT서비스
2      반도체
4      바이오
5     자율주행
dtype: object

In [40]:
np.random.seed(0)
sample = pd.Series(np.random.randint(100,200,size=(10,)))
sample[2:7]

2    164
3    167
4    167
5    109
6    183
dtype: int32

In [41]:
np.random.seed(0)
sample2 = pd.Series(np.random.randint(100,200,size=(10,)), index = list('가나다라마바사아자차'))
sample2['바':'차']

바    109
사    183
아    121
자    136
차    187
dtype: int32

In [42]:
sample2["가":"다"]

가    144
나    147
다    164
dtype: int32